# Generated by Django 5.0.6 on 2024-07-30 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_project_file_name_alter_file_file_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
