# Generated by Django 5.0.6 on 2024-08-16 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientcompanyfolder_clientcompanyfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompanyCalendar',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'company',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companyCalendar',
                        to='client.clientcompanyprofile',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ClientCompanyEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'calendar',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='companyEvents',
                        to='client.clientcompanyprofile',
                    ),
                ),
                (
                    'participants',
                    models.ManyToManyField(
                        blank=True, related_name='companyEvents', to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
