# Generated by Django 5.0.6 on 2024-08-21 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clientcompanyevent_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='employee_profile',
            field=models.ManyToManyField(
                blank=True, related_name='companies', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
