# Generated by Django 5.0.6 on 2024-10-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_permission_rename_phone_personalinfo_contact_number_and_more'),
        ('client', '0008_clientcompanyprofile_email_clientcompanyprofile_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='countryName',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='formalName',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='personal_info',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='client_profile',
                to='accounts.personalinfo',
            ),
        ),
    ]
