# Generated by Django 5.0.6 on 2024-10-06 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_permission_rename_phone_personalinfo_contact_number_and_more'),
        ('client', '0009_remove_clientprofile_countryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='personal_info',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.personalinfo',
            ),
        ),
    ]
