# Generated by Django 5.0.6 on 2024-07-03 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='specializations',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='technicalProficiencies',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='CrewCredits',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('year', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(blank=True, max_length=256, null=True)),
                ('production', models.CharField(blank=True, max_length=256, null=True)),
                ('client', models.CharField(blank=True, max_length=256, null=True)),
                ('type_of_content', models.CharField(blank=True, max_length=256, null=True)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CrewEducation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('academicQualifications', models.CharField(blank=True, max_length=256, null=True)),
                ('professionalCourses', models.CharField(blank=True, max_length=256, null=True)),
                ('workshopsAttended', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CrewRate',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('standardRate', models.CharField(blank=True, max_length=256, null=True)),
                ('negotiation', models.BooleanField(default=False)),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='EndorsementfromPeers',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('text', models.TextField(blank=True, null=True)),
                ('givenBy', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
    ]
