# Generated by Django 5.0.6 on 2024-08-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_crewcalendar_crewevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewevent',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='crewevent',
            old_name='start_time',
            new_name='start',
        ),
    ]
