# Generated by Django 5.0.6 on 2024-08-12 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_rename_end_time_crewevent_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReferenceVerification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='standardRate',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='CrewPortfolio',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                (
                    'image',
                    models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnail/'),
                ),
                ('contentTag', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('providedService', models.TextField(blank=True, null=True)),
                (
                    'verification_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('client_reference', 'Client Reference'),
                            ('imbd_link', 'IMDB Link'),
                            ('work_sample', 'Work Sample'),
                            ('email_agreement', 'Email Agreement'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ('verified', models.BooleanField(default=False)),
                (
                    'client_reference_verification',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='crew.clientreferenceverification',
                    ),
                ),
                (
                    'crew',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewprofile'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='clientreferenceverification',
            name='crew_portfolio',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='crew.crewportfolio'
            ),
        ),
        migrations.CreateModel(
            name='EmailAgreement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'document',
                    models.FileField(blank=True, null=True, upload_to='portfolio/document/'),
                ),
                (
                    'crew_portfolio',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewportfolio'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='crewportfolio',
            name='email_agreement_verification',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crew.emailagreement',
            ),
        ),
        migrations.CreateModel(
            name='ImbdLinkVerification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('link', models.URLField()),
                (
                    'crew_portfolio',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewportfolio'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='crewportfolio',
            name='imbd_link_verification',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crew.imbdlinkverification',
            ),
        ),
        migrations.CreateModel(
            name='WorkSampleVerification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('minutes', models.PositiveIntegerField()),
                ('seconds', models.PositiveIntegerField()),
                (
                    'crew_portfolio',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='crew.crewportfolio'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='crewportfolio',
            name='work_sample_verification',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='crew.worksampleverification',
            ),
        ),
    ]
