# Generated by Django 5.0.6 on 2024-08-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_clientreferenceverification_crewprofile_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrewRate',
        ),
    ]
