# Generated by Django 5.0.6 on 2024-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_delete_crewrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
