# Generated by Django 5.0.6 on 2024-10-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_permission_rename_phone_personalinfo_contact_number_and_more'),
        ('crew', '0006_delete_crewrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='crewprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='personal_info',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='crew_profile',
                to='accounts.personalinfo',
            ),
        ),
    ]
