# Generated by Django 5.0.6 on 2024-09-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_inboxgroup_inboxmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inboxmessage',
            old_name='content',
            new_name='message',
        ),
    ]
