# Generated by Django 5.0.6 on 2024-10-15 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_crewrequirements_equipmentrequirements_permission_and_more'),
        ('tasks', '0002_task_completion_requested_task_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                (
                    'assigned_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_tasks_by',
                        to='project.membership',
                    ),
                ),
                (
                    'assigned_to',
                    models.ManyToManyField(related_name='project_tasks', to='project.membership'),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_tasks',
                        to='project.projectdetails',
                    ),
                ),
            ],
        ),
    ]
