# Generated by Django 4.2.13 on 2024-07-01 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode_of_shooting', models.CharField(max_length=255)),
                ('permits', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'project_id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('additional_details', models.TextField()),
                ('budget_currency', models.CharField(default='$', max_length=256)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('content_type', models.CharField(max_length=256)),
                ('selected_crew', models.TextField()),
                ('equipment', models.TextField()),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PLANNING', 'Planning'),
                            ('IN_PROGRESS', 'In Progress'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                            ('PAUSED', 'Paused'),
                            ('DEVELOPMENT', 'Development'),
                            ('PRE_PRODUCTION', 'Pre-Production'),
                            ('POST_PRODUCTION', 'Post-Production'),
                            ('RELEASED', 'Released'),
                        ],
                        default='PLANNING',
                        max_length=30,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'location_details',
                    models.ManyToManyField(related_name='projects', to='project.locationdetail'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
    ]
