# Generated by Django 5.0.6 on 2024-07-05 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_onboardrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboardrequest',
            old_name='crew',
            new_name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='crew_profiles',
            field=models.ManyToManyField(
                blank=True, related_name='projects', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
