# Generated by Django 5.0.6 on 2024-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_location_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location_details',
            field=models.ManyToManyField(
                blank=True, related_name='projects', to='project.locationdetail'
            ),
        ),
    ]
