# Generated by Django 4.2.13 on 2024-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_location_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location_details',
            field=models.ManyToManyField(related_name='projects', to='project.locationdetail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_documents/'),
        ),
    ]
