# Generated by Django 5.0.6 on 2024-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_uploaded_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bucket_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_folder',
        ),
        migrations.AlterField(
            model_name='project',
            name='uploaded_document',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_documents/'),
        ),
    ]
