# Generated by Django 5.0.6 on 2024-07-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_bucket_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCrew',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectEquipment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected_crew',
        ),
        migrations.AddField(
            model_name='project',
            name='equipment',
            field=models.ManyToManyField(
                related_name='SelectEquipment', to='project.selectequipment'
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='selected_crew',
            field=models.ManyToManyField(related_name='SelectCrew', to='project.selectcrew'),
        ),
    ]
