# Generated by Django 5.0.6 on 2024-09-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_document_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(related_name='uploaded_documents', to='project.document'),
        ),
    ]
