# Generated by Django 5.0.6 on 2024-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_steps_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='steps',
            field=models.BooleanField(default=False),
        ),
    ]
