# Generated by Django 5.0.6 on 2024-10-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
