# Generated by Django 5.0.6 on 2024-10-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_user_type_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
