# Generated by Django 5.0.6 on 2024-10-05 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_usertype_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('languages', models.CharField(blank=True, max_length=256, null=True)),
                ('job_title', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=256, null=True)),
                ('skills', models.CharField(blank=True, max_length=256, null=True)),
                ('standardRate', models.CharField(blank=True, max_length=256, null=True)),
                ('technicalProficiencies', models.CharField(blank=True, max_length=256, null=True)),
                ('specializations', models.CharField(blank=True, max_length=256, null=True)),
                ('drive', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
