# Generated by Django 5.0.6 on 2024-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='active',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='drive',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='standardRate',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='technicalProficiencies',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='permissions',
        ),
        migrations.AddField(
            model_name='usertype',
            name='permissions',
            field=models.ManyToManyField(
                blank=True, related_name='user_types', to='accounts.permission'
            ),
        ),
    ]
