# Generated by Django 5.0.6 on 2024-10-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_permission_rename_phone_personalinfo_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100, unique=True)),
                ('alpha_2_code', models.CharField(max_length=2, unique=True)),
                ('alpha_3_code', models.CharField(max_length=3, unique=True)),
                ('numeric_code', models.CharField(max_length=4, unique=True)),
            ],
        ),
    ]
