# Generated by Django 5.0.6 on 2024-07-07 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyvord_calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(
                blank=True, related_name='events', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
