# Generated by Django 5.0.6 on 2024-08-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storyvord_calendar', '0002_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='start',
        ),
    ]
