# Generated by Django 5.0.6 on 2024-08-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyvord_calendar', '0003_rename_end_time_event_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
