# Generated by Django 5.0.6 on 2024-07-19 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0008_remove_project_bucket_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('calltime', models.TimeField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=255)),
                ('producer_number', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=255)),
                ('director_number', models.CharField(max_length=20)),
                ('production_manager', models.CharField(max_length=255)),
                ('production_manager_number', models.CharField(max_length=20)),
                ('breakfast', models.TimeField()),
                ('lunch', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('sunset', models.TimeField()),
                ('weather', models.CharField(blank=True, max_length=255)),
                ('nearest_hospital_address', models.CharField(blank=True, max_length=255)),
                ('nearest_police_station', models.CharField(blank=True, max_length=255)),
                ('nearest_fire_station', models.CharField(blank=True, max_length=255)),
                ('additional_details', models.TextField(blank=True)),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'project',
                    models.ForeignKey(
                        default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'
                    ),
                ),
            ],
        ),
    ]
