# Generated by Django 5.0.6 on 2024-07-28 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0009_selectcrew_selectequipment_remove_project_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('calltime', models.TimeField()),
                ('breakfast', models.TimeField()),
                ('lunch', models.TimeField()),
                ('additional_details', models.TextField(default='No additional details provided')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('producer', models.CharField(blank=True, max_length=255)),
                ('producer_number', models.CharField(blank=True, max_length=20)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('director_number', models.CharField(blank=True, max_length=20)),
                ('nearest_hospital_address', models.CharField(blank=True, max_length=255)),
                ('nearest_police_station', models.CharField(blank=True, max_length=255)),
                ('nearest_fire_station', models.CharField(blank=True, max_length=255)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='project.project'
                    ),
                ),
            ],
        ),
    ]
