# Generated by Django 5.0.6 on 2024-07-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('calltime', models.TimeField()),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('producer', models.CharField(max_length=255)),
                ('producer_number', models.CharField(max_length=20)),
                ('director', models.CharField(max_length=255)),
                ('director_number', models.CharField(max_length=20)),
                ('production_manager', models.CharField(max_length=255)),
                ('production_manager_number', models.CharField(max_length=20)),
                ('breakfast', models.CharField(blank=True, max_length=255)),
                ('lunch', models.CharField(blank=True, max_length=255)),
                ('sunrise', models.TimeField(blank=True)),
                ('sunset', models.TimeField(blank=True)),
                ('weather', models.CharField(blank=True, max_length=255)),
                ('nearest_hospital_address', models.CharField(blank=True, max_length=255)),
                ('nearest_police_station', models.CharField(blank=True, max_length=255)),
                ('nearest_fire_station', models.CharField(blank=True, max_length=255)),
                ('additional_details', models.TextField(blank=True)),
            ],
        ),
    ]
