# Generated by Django 5.0.6 on 2024-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsheet',
            name='breakfast',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='calltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callsheet',
            name='lunch',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
