# Generated by Django 5.0.6 on 2024-07-18 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='location',
            field=models.CharField(default='To be determined', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callsheet',
            name='project_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
