# Generated by Django 5.0.6 on 2024-08-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0002_alter_callsheet_breakfast_alter_callsheet_calltime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callsheet',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='city',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='country',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='director',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='director_number',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='location',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='producer_number',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='street',
        ),
        migrations.RemoveField(
            model_name='callsheet',
            name='website',
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('character_name', models.CharField(max_length=255)),
                ('actor', models.CharField(blank=True, max_length=255)),
                ('status', models.TimeField(blank=True, null=True)),
                ('pickup', models.TimeField(blank=True, null=True)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('makeup', models.TimeField(blank=True, null=True)),
                ('costume', models.TimeField(blank=True, null=True)),
                ('rehearsal', models.TimeField(blank=True, null=True)),
                ('on_set', models.TimeField(blank=True, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentInstructions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('department', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=255)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('scene_number', models.CharField(max_length=255)),
                ('extra', models.CharField(max_length=255)),
                ('arrival', models.TimeField(blank=True, null=True)),
                ('makeup', models.TimeField(blank=True, null=True)),
                ('costume', models.TimeField(blank=True, null=True)),
                ('rehearsal', models.TimeField(blank=True, null=True)),
                ('on_set', models.TimeField(blank=True, null=True)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('scene_number', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('cast', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('other_notes', models.TextField(blank=True, null=True)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('temperature', models.IntegerField()),
                ('conditions', models.CharField(max_length=255)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='callsheets.callsheet'
                    ),
                ),
            ],
        ),
    ]
