# Generated by Django 5.0.6 on 2024-07-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0002_callsheet_created_at_callsheet_location_and_more'),
        ('project', '0008_remove_project_bucket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='project',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='project.project'
            ),
        ),
    ]
