# Generated by Django 5.0.6 on 2024-09-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0004_alter_characters_call_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
