# Generated by Django 5.0.6 on 2024-09-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0005_callsheet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentinstructions',
            name='call_sheet',
        ),
        migrations.RemoveField(
            model_name='extras',
            name='call_sheet',
        ),
        migrations.RemoveField(
            model_name='scenes',
            name='call_sheet',
        ),
        migrations.AddField(
            model_name='callsheet',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='production_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CallTime',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('calltime', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                (
                    'call_sheet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='call_time',
                        to='callsheets.callsheet',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Characters',
        ),
        migrations.DeleteModel(
            name='DepartmentInstructions',
        ),
        migrations.DeleteModel(
            name='Extras',
        ),
        migrations.DeleteModel(
            name='Scenes',
        ),
    ]
