# Generated by Django 5.0.6 on 2024-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0006_remove_departmentinstructions_call_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='breakfast',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='dinner',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callsheet',
            name='lunch',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='sunset',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
