# Generated by Django 5.0.6 on 2024-09-24 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0007_callsheet_breakfast_callsheet_dinner_callsheet_lunch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callsheet',
            name='allowed_users',
            field=models.ManyToManyField(
                blank=True, related_name='callsheets', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
