# Generated by Django 5.0.6 on 2024-10-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0008_callsheet_allowed_users'),
        ('crew', '0007_sociallinks_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltime',
            name='email',
        ),
        migrations.RemoveField(
            model_name='calltime',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calltime',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='calltime',
            name='position',
        ),
        migrations.AddField(
            model_name='calltime',
            name='crew_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='call_times',
                to='crew.crewprofile',
            ),
        ),
    ]
