# Generated by Django 5.0.6 on 2024-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsheets', '0009_remove_calltime_email_remove_calltime_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
