# Generated by Django 5.0.6 on 2024-08-13 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='recipients',
            field=models.ManyToManyField(
                blank=True, related_name='announcements', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
