# Generated by Django 5.0.6 on 2024-08-20 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='pants_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='pronouns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='AddressBookCateringInformation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('specific', models.TextField()),
                ('allergies', models.TextField()),
                ('note', models.TextField()),
                ('food_preferences', models.TextField()),
                (
                    'address_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='company.addressbook'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AddressBookFiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('file', models.FileField(upload_to='address_book_files/')),
                (
                    'address_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='company.addressbook'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AddressBookHomeAddress',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                (
                    'address_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='company.addressbook'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AddressBookSkills',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('certification', models.CharField(max_length=256)),
                ('education_and_training', models.TextField()),
                ('driving_license', models.CharField(max_length=50)),
                ('driving_license_classes', models.CharField(max_length=256)),
                (
                    'address_book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='company.addressbook'
                    ),
                ),
            ],
        ),
    ]
