# Generated by Django 5.0.6 on 2024-08-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
