# Generated by Django 5.0.6 on 2024-08-21 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientprofile_employee_profile'),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvitation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('employee_email', models.EmailField(max_length=254)),
                ('referral_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('accepted', 'Accepted'),
                            ('rejected', 'Rejected'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'client_profile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='client.clientprofile'
                    ),
                ),
            ],
        ),
    ]
